# Generated by Django 2.2.6 on 2019-11-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiqu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='pingtai',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
